# Cloud build file structure: https://cloud.google.com/build/docs/deploying-builds/deploy-functions
# Since using gcloud, we can add any flag that is supported by the "gcloud functions deploy" command (https://cloud.google.com/sdk/gcloud/reference/functions/deploy)
steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - helloCloudBuild
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=nodejs16
      - --allow-unauthenticated
      - --ingress-settings=all
      - --gen2
