steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - helloCloudBuild
      - --source=.
      - --trigger-http
      - --runtime=nodejs14
      - --allow-unauthenticated
      - --ingress-settings=all
