steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - helloCloudBuild
      - --source=.
      - --trigger-http
      - --runtime=nodejs8
      - --allow-unauthenticated