steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - functions
      - deploy
      - helloCloudBuild
      - --source=.
      - --trigger-http
      - --runtime=nodejs8
      - --allow-unauthenticated
      - --ingress-settings=all
