# This is a basic workflow to help you get started with Actions

name: gcs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: GCP Storage
      uses: convictional/gcp-storage-action@v0.1.1
      with:
        # The file path that the file will be sourced from. This can be either a local file or GCP storage file. GCP storage file should lead with gs://.
        source_file: 
        # The file path that the file will be uploaded to. This can be either a local file or GCP storage file.
        destination_file: 
        # These are the IAM credentials for accessing the GCP bucket.
        application_credentials: # optional
        # The project id that the bucket lives under.
        project_id: # optional
        # The action to be performed. This defaults to cp and isnt implemented yet.
        action: # optional
        # Additional flags to be passed in.
        flags: # optional
